export const projectsData = [
  {
    id: 1,
    title: "CircuitSetu",
    description:
      "A high-performance circuit simulator using a C++ WASM engine for real-time, privacy-first engineering in your browser.",
    github: "https://github.com/r17e8h/CircuitSetu/",
    tech: ["C++", "WebAssembly", "Next.js", "React Native"],
    year: "Feb 2026",
    stars: 11,
    imageLight: "/ippo1.gif",
    imageDark: "/berserk-gif-18.gif",
  },
  {
    id: 2,
    title: "EnPassant",
    description: "Tactical transaction security, executed in milliseconds.",
    github: "https://github.com/r17e8h/EnPassant/",
    tech: ["C++", "Python", "TypeScript"],
    year: "Aug 2026",
    stars: 2,
    imageDark: "/berserk-gif.gif",
    imageLight: "/ippo2.gif",
  },
  {
    id: 3,
    title: "r17e8h-chess_bot",
    description:
      "A custom chess engine trained using behavioral cloning to replicate my personal playstyle. ",
    tech: ["Python", "Shell", "PyTorch"],
    github: "https://github.com/r17e8h/r17e8h-chess_bot/",
    year: "June 2026",
    stars: 2,
    imageDark: "/berserk3.gif",
    imageLight: "/ippo3.gif",
  },
  {
    id: 4,
    title: "3000",
    description: "terminal based screensaver",
    tech: ["Python"],
    github: "https://github.com/r17e8h/3000/",
    year: "July 2026",
    stars: 3,
    imageDark: "/berserk4.gif",
    imageLight: "/ippo4.gif",
  },
  {
    id: 5,
    title: "OpenTick",
    description:
      "lightweight CLI tool that combines to-do lists, time tracking, habit tracking and daily journaling directly in your terminal.",
    tech: ["Shell"],
    github: "https://github.com/r17e8h/OpenTick",
    year: "Jan 2026",
    stars: 2,
    imageDark: "/berserk5.gif",
    imageLight: "/ippo5.gif",
  },
];
